# POSCO 시스템 CI/CD 파이프라인 설정
# Continuous Integration/Continuous Deployment Configuration

# 파이프라인 스테이지 설정
stages:
  - name: syntax_check
    enabled: true
    timeout: 300
    description: "Python 구문 오류 검사"
    
  - name: import_test
    enabled: true
    timeout: 180
    description: "모듈 Import 테스트"
    
  - name: unit_test
    enabled: true
    timeout: 600
    description: "단위 테스트 실행"
    
  - name: integration_test
    enabled: true
    timeout: 900
    description: "통합 테스트 실행"
    
  - name: performance_test
    enabled: true
    timeout: 1200
    description: "성능 테스트 및 리소스 사용량 검증"
    
  - name: security_scan
    enabled: true
    timeout: 300
    description: "보안 취약점 스캔"
    
  - name: quality_gate
    enabled: true
    timeout: 60
    description: "품질 게이트 검증"

# 알림 설정
notifications:
  enabled: true
  on_failure: true
  on_success: false
  channels:
    - type: log
      level: info
    - type: file
      path: "./ci_notifications.log"

# 아티팩트 설정
artifacts:
  retention_days: 30
  storage_path: "./ci_artifacts"
  types:
    - test_reports
    - performance_data
    - security_scan_results
    - quality_metrics

# 품질 기준 설정
quality_thresholds:
  syntax_errors: 0
  import_failures: 0
  test_coverage: 80.0
  performance:
    cpu_usage: 80.0
    memory_usage: 85.0
    response_time: 5.0
    startup_time: 10.0
  security:
    max_issues: 10
    critical_issues: 0

# 환경 설정
environment:
  python_version: "3.8+"
  required_packages:
    - psutil
    - pyyaml
    - schedule
  
# 스케줄 설정
schedule:
  # 매일 오전 2시에 전체 파이프라인 실행
  daily_full_pipeline: "0 2 * * *"
  # 매시간 건강성 체크
  hourly_health_check: "0 * * * *"
  # 매 15분마다 빠른 검증
  quick_check: "*/15 * * * *"